yast/yast-ruby-bindings

.travis.yml, tests/ruby/builtins_spec.rb
- for some reason `LC_ALL` needs to be set when testing locale dependent code
- disable some `crypt()` tests (do not work in Ubutu, unfortunately this is deep in glibc and cannot be easily fixed)
=> Run tests at Travis

CMakeLists.txt, package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
https://bugzilla.novell.com/show_bug.cgi?id=914255
=> Fix building with yast2-core-3.1.16: use C++11 like core does

src/binary/Builtin.cc
The manual says it is actually harmless.
Mismatched free() / delete / delete []
http://valgrind.org/docs/manual/mc-manual.html#mc-manual.rudefn
https://bugzilla.suse.com/show_bug.cgi?id=932306
=> Fixed a strdup/delete mismatch (boo#932306).

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/path.rb, src/ruby/yast/term.rb, tests/ruby/ops_spec.rb, tests/ruby/path_spec.rb, tests/ruby/term_spec.rb
https://bugzilla.suse.com/show_bug.cgi?id=933470
Term and Path would raise exceptions when <=> was used to compare them
with something that was not a Term or Path.
In particular it happened during RSpec argument matching.
In older Ruby core, Comparable#== would silently mask such exceptions,
now it started producing warnings.
https://bugs.ruby-lang.org/issues/7688
=> Fixed "Comparable#== will no more rescue exceptions of #<=>" (bsc#933470)

.travis.yml, package/yast2-ruby-bindings.spec, tests/ruby/CMakeLists.txt, tests/ruby/integration/run.rb, tests/ruby/integration/std_streams_spec.rb, tests/ruby/std_streams_spec.rb
I didn't manage to write a test reproducing the bug in libyui-test, so I wrote a test here (which, on the other hand, fits better the bug description, since YaST and Ruby are involved).
Should we add ```BuildRequires: libyui-ncurses >= 2.47.3``` to the spec file? I find it a little bit overkill, but I'm open to suggestions.
This can be merged after https://github.com/libyui/libyui-ncurses/pull/40 or https://github.com/libyui/libyui-ncurses/pull/41 (whichever wins the contest), since both make the test happy.
=> Test for bnc#943757, fixed in libyui-ncurses 2.47.3

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/logger.rb, tests/ruby/y2logger_spec.rb
- 3.1.43
Fixes https://bugzilla.suse.com/show_bug.cgi?id=932014
=> Do not crash when logging an invalid UTF-8 string (bsc#932014)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/logger.rb
Fixes conflict between `Yast::Encoding` and `::Encoding` (from std Ruby).
=> Fix Encoding name conflict

.rubocop.yml, package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/debugger.rb, src/ruby/yast/wfm.rb, tests/ruby/y2logger_spec.rb
- Added `yast/debugger` for generic handling of the Ruby debugger (to be used in the installer, see [FATE#318421](https://fate.suse.com/318421), the installer part is implemented in this PR: https://github.com/yast/yast-installation/pull/379).
- Allow running the debugger from the generic crash handler, see the screenshots below.
The original generic crash handler displays a popup like this:
With this patch when the `byebug` Ruby gem is installed it displays this:
Which when confirmed starts the debug session in a new `xterm` window:
In the text mode we cannot start the `xterm` session automatically, you have to start the debugger front end manually:
=> Debugger support

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/debugger.rb, src/ruby/yast/wfm.rb
Use the same code also at run time, allow using `Y2DEBUGGER` also in installed system.
Now you can run `Y2DEBUGGER=1 yast2 <client>` and the debugger window will automatically pop up.
- 3.1.48
=> Improve the debugger support (FATE#318421)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/wfm.rb
[bsc#992821](https://bugzilla.suse.com/show_bug.cgi?id=992821)
=> Rescue "invalid byte sequence in UTF-8", with a custom message

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Yast.cc
Hook to the `UI::` calls and detect the debug magic key event, start the Ruby debugger when it is received.
- The debugger can be started during installation or in installed system when needed, e.g. you see a strange value in a dialog, simply pressing `Shift`+`Ctrl`+`Alt`+`D` starts the debugger and you can inspect the internal state immediately
- Only the Qt UI can send the debugging magic key (i.e. it does not work in ncurses)
- The debugger can be started only from `UI::UserInput()` and similar calls
- If the code does not interact with user (e.g. it's waiting for an external command to finish or is cycling in an infinite loop) the debugger cannot be started
Although there are some disadvantages of this solution it is a big step forward for easier YaST debugging.
=> Add debugger hooks

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
This is basically a backport of #177 to SP2.
Additional changes:
- Keep the same version, this is not an urgent bug fix. It will be released later with some other real fix.
=> Debugger - backport to SP2

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Yast.cc
Hook to the `UI::` calls and detect the debug magic key event, start the Ruby debugger when it is received.
We have improved the Ruby debugger integration in YaST. So far you could start the debugger using the `y2debugger=1` boot option or by setting the `Y2DEBUGGER=1` environment variable. The new feature allows starting the Ruby debugger also later when the YaST module is already running.
Simply press `Shift`+`Ctrl`+`Alt`+`D` magic key combination (`D` as debug) and it will start the Ruby debugger. It works during installation and also in installed system (just make sure the `byebug` Ruby gem is installed).
Unfortunately this new feature works only in the Qt UI, the ncurses UI is not supported (it currently does not handle the magic keyboard combination).
=> Debugger hooks

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/i18n.rb, tests/ruby/i18n_spec.rb
Try to be more robust to avoid [bsc#1014458](https://bugzilla.suse.com/show_bug.cgi?id=1014458).
It looks like the problem is related to the update of fast_gettext. Once that package has been updated, the`/usr/lib64/ruby/gems/2.1.0/gems/fast_gettext-0.8.1/lib/fast_gettext/vendor/empty.mo` does not exist anymore (now is `/usr/lib64/ruby/gems/2.1.0/gems/fast_gettext-0.9.2/lib/fast_gettext/vendor/empty.mo`).
I think that the crash comes from [this line](https://github.com/grosser/fast_gettext/blob/fa8da8d6947108955450b1d0b515e32a36ee5c38/lib/fast_gettext/translation_repository/mo.rb#L41) which calls [MoFile.empty](https://github.com/grosser/fast_gettext/blob/fa8da8d6947108955450b1d0b515e32a36ee5c38/lib/fast_gettext/mo_file.rb#L39).
I haven't been able to reproduce it, but I think that this …
=> Do not crash when empty.mo is missing

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, tests/integration/run.rb
Trying to figure out what's going on here https://build.opensuse.org/request/show/460505 since it cannot be reproduced out of OBS.
=> Display output of failed headless integration tests

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/wfm.rb
how output now looks like ( with testing client that just raise error ):
```
2017-09-26 15:19:23 <3> pepa(2635) [Ruby] yast/wfm.rb:253 Client call failed with 'funny' (RuntimeError).
Backtrace:
/tmp/test.rb:1:in `<top (required)>'
/usr/lib64/ruby/vendor_ruby/2.4.0/yast/wfm.rb:300:in `eval'
/usr/lib64/ruby/vendor_ruby/2.4.0/yast/wfm.rb:300:in `run_client'
/usr/lib64/ruby/vendor_ruby/2.4.0/yast/wfm.rb:206:in `call_builtin'
/usr/lib64/ruby/vendor_ruby/2.4.0/yast/wfm.rb:206:in `call_builtin_wrapper'
/usr/lib64/ruby/vendor_ruby/2.4.0/yast/wfm.rb:195:in `CallFunction'
/usr/lib/YaST2/bin/y2start:56:in `<main>'
```
=> Nicer backtrace

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/i18n.rb
- This helps with debugging so the missing `textdomain` calls can be easier found.
- Writing the caller to the log helps to find the place where the translation call was used incorrectly. Grepping the sources for the label is a bit tricky if it contains the `&` shortcut marker or `%s` placeholders.
- 4.0.5
I have tested this when fixing bug https://github.com/yast/yast-network/pull/619, now the problematic place is logged into y2log:
```
2018-03-27 13:31:49 <2> dhcp25(24521) [Ruby] yast/i18n.rb:47 No textdomain configured, ca
nnot translate text "Enable access using a &web browser"
2018-03-27 13:31:49 <2> dhcp25(24521) [Ruby] yast/i18n.rb:48 Called from: /usr/share/YaST
2/lib/y2remote/widgets/remote.rb:165:in `label'
```
=> Log a warning if no text domain is configured (bsc#1081466)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/wfm.rb
Depends on https://github.com/yast/yast-yast2/pull/899
When an internal error with long backtrace is raised, it gets easily out of popup:
With support for long text it is slightly better:
=> Fit long internal error to the screen

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/i18n.rb, tests/i18n_spec.rb
*This is a proposal for the fix discussed on yast-devel@ ML, lets continue here.*
The `_()` translation function returns either a frozen String (from FastGettext when the translation is available) or a normal (not frozen) String when the translation is not found.
This makes the code fragile and difficult to debug as `_("foo") << _("bar")` might crash or might not depending whether the translation is available.
The problem is that when running the unit tests in Travis, Jenkins or in OBS no translation is installed and the tests run in the English locale. However, on user systems or during installation the translations are usually available. That means it's hard to test it in the same environment, the unit tests might not find this problem in the code.
Moreover the translations for new …
=> _() should always return a frozen string

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/i18n.rb
In https://bugzilla.suse.com/show_bug.cgi?id=1130822 we have untranslated text in a dialog, even though the translators did work that particular string. The reason is a missing `textdomain` declaration in a class.
This kind of error is a programmer error which should be caught very early during the development or testing, so users should not see them. 
BUT we may have allowed this kind of bugs to creep in over time so it would be a nuisance to start failing in users faces now.
-> Make it opt-in for testing.
The exception is enabled by export Y2STRICTTEXTDOMAIN=1
=> A missing `textdomain` declaration is optionally an exception

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/i18n.rb
A fixup for #230 - https://bugzilla.suse.com/show_bug.cgi?id=1130822#c13
If /usr/share/YaST2/locale does not exist (eg. during the building of yast2.rpm) FastGettext will complain. So in that case bail out of `textdomain` and `_`+friends.
Here's how it broke without this fix:
+Log	No textdomain configured in Yast::CommandLineClass, cannot translate "Print the help for this module"
The log line *appears* because it is now reported at CommandLine.rb
(previously i18n.rb) which matches the "testedfiles" filter of the
testsuite.
The error *happens* the "textdomain" method returns early before
remembering its argument.
=> Avoid breaking the build of yast2.rpm (bsc#1130822)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/ui_shortcuts.rb
https://trello.com/c/dcDDFwGy/1405-5-allow-additional-status-values-in-multiitemselector
This adds the new `CustomStatusItemSelector` widget as well as the old `icon` term that for some reason was never added to those UI shortcuts, always making a pretty ugly `term(:icon("iconName"))` necessary.
=> New Ui Widget

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/y2start_helpers.rb, src/y2start/y2start, tests/integration/run.rb, tests/y2start_helpers_spec.rb
Implement proper exit codes of yast program
It is currently identical behavior as in original y2core.
References:
https://github.com/yast/yast-core/blob/master/liby2/src/genericfrontend.cc#L777
https://github.com/yast/yast-core/blob/master/liby2/src/include/y2/exitcodes.h#L25
https://github.com/yast/yast-core/blob/master/liby2/src/genericfrontend.cc#L115
replaces https://github.com/yast/yast-ruby-bindings/pull/222
=> Exit codes

COPYING, package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
Stanislav Brabec reported this repository has COPYING or LICENSE file, although GPL 2 was mentioned in the header of the source code files.
See https://bugzilla.suse.com/show_bug.cgi?id=1161470
This pull request fixes the issue and also includes the license in the RPM package, as other YaST packages do.
=> Added COPYING file with the GPL license

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/YRuby.cc
Fix is needed for MU of ruby on SLE12 SP2. See https://bugzilla.suse.com/show_bug.cgi?id=1172275 for references. Patch was provided by @darix
Change for newer SP is not needed as we start using y2start from SP3.
=> Fix enc loading

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/YRuby.cc
https://bugzilla.suse.com/show_bug.cgi?id=1172848
https://trello.com/c/tZ9MKejZ/
An appliance made with SUSE Studio (i.e. using KIWI) based on SLE-12-SP4 fails since the last Ruby security update in their yast-firstboot step where they do various configurations after extracting their image.
It turned out that they are invoking other YaST modules (e.g. network) as external processes by invoking `y2base` directly.
Ruby does not really have an API for embedding; to integrate it into YaST, we really hammered it into shape to make it work. That involved loading some Ruby gems early upon YaST startup: E.g. the `fast_gettext` gem which we use for translations. How this is done tends to differ slightly between individual Ruby versions, so it has to be adapted when that happens.
- Backported some …
=> Backport to SLE-12-SP4: Fix Gem Loading

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/YRuby.cc
**This is the SLE-12-SP5 version of PR https://github.com/yast/yast-ruby-bindings/pull/244**.
Refer to https://github.com/yast/yast-ruby-bindings/pull/244 for details.
=> Backport to SLE-12-SP5

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/YRuby.cc
A security fix for Ruby was released for SLE-12-SP2, SP3, SP4 and SP5... that broke YaST.
The fix for SP2 was introduced in #242 and #243. The original plan was to not port that fix to the SLE-12-SP3 branch. But after some discussions in [bsc#1172848](https://bugzilla.suse.com/show_bug.cgi?id=1172848), it was decided to make it available for SLE-12-SP3-LTSS.
Tested manually in a SLE-12-SP3-LTSS. Verified it indeed fixes the problem.
=> Port from SP2 to SP3 of the fix for newer versions of Ruby

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/ui_shortcuts.rb
https://trello.com/c/4GtDpmMo/1956-5-menu-bar-widget
This adds some new UI terms to the Ruby bindings:
- `MenuBar(...)`
- `Menu(...)`
Alternatively, it was (and is) also possible to use
```Ruby
term(:MenuBar, ...)
```
```Ruby
term(:menu, ...)
```
But having the terms directly makes the code cleaner and better readable.
https://github.com/libyui/libyui/pull/169
=> New Widget: MenuBar

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Builtin.cc, tests/builtins_spec.rb
follow up of https://github.com/yast/yast-ruby-bindings/pull/239
I clean this up to support only the latest libxcrypt as it is already in SLE15 SP3, Leap 15.3 and TW.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1176924
=> Crypt improvements

package/yast2-ruby-bindings.spec
rpmbuild fails without the fix. Corrected if statement to work with rpmbuild.
=> Fixed if statement in yast2-ruby-bindings.spec

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/debugger.rb, src/ruby/yast/wfm.rb
https://trello.com/c/NaUW5kuD/2142-3-sles12-sp4-p3-1127906-augeas-exception-raised-to-the-user-when-a-malformed-grubcmdlinelinuxdefault-is-found
A backport from SLES15-SP2:
https://github.com/yast/yast-ruby-bindings/pull/253
=> Distinguish parsing errors from internal errors (bsc#1127906)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, tests/libyui/multi_selection_box_spec.rb, tests/libyui/rspec_tmux_tui.rb
Continues #254.
@shundhammer if you make your PRs from a branch in the team repo instead of from your fork then we will be able to push to that branch and keep the same PR instead of needlessly creating a new one. thanks :smiley: 
Copying that PR's description, minus the *Problems* section since they are solved in this PR.
https://trello.com/c/ZbkIbc0M/2133-3-probable-libyui-regressions-p1-1177985-and-p1-1177982
This tests some basic features of the MultiSelectionBox as well as the regression that was just fixed in https://github.com/libyui/libyui-ncurses/pull/108 .
It uses this new UI example from https://github.com/libyui/libyui-ncurses/pull/108 :
https://github.com/yast/yast-ycp-ui-bindings/blob/master/examples/MultiSelectionBox-test.rb
=> UI Unit Tests for MultiSelectionBox

tests/libyui/multi_selection_box_spec.rb
Update for https://github.com/yast/yast-ruby-bindings/pull/256 :
Changed misleading comment: Alt-V already toggled the `[ ] Vegetarian` check box; the subsequent Space key toggled the selected status of the current item which was not intended.
Now also checking if the new selection is correct after toggling that check box: If vegetarian, it also selects "Mushrooms", otherwise "Salami".
=> Removed misleading double-toggling veggie checkbox

tests/builtins_regexps_spec.rb, tests/integration/run.rb, tests/integration/std_streams_spec.rb
Failing build: (likewise on ci.o.o and ci.s.d)
- https://ci.suse.de/view/YaST/job/yast-yast-ruby-bindings-master/26/console
Fixed build:
- https://ci.opensuse.org/view/Yast/job/yast-yast-ruby-bindings-mvidner/4/console
BTW I made a testing Jenkins job to debug and fix this: New project by copying the *yast-yast-ruby-bindings-master* project, then:
1. change the branch from `master` to `mvidner-test`
2. change the rake target from `osc:sr` to `osc:build` :exclamation:
=> Fix Jenkins build "Error opening terminal: unknown"

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, tests/libyui/menu_item_spec.rb, tests/libyui/table_sort_spec.rb
- bug https://bugzilla.opensuse.org/show_bug.cgi?id=1178394
- the fix is https://github.com/libyui/libyui-qt/pull/139
- half of test case https://github.com/yast/yast-ycp-ui-bindings/pull/60
- this is the other half
Well, sort of. The bug is in libyui-qt and we test libyui-ncurses. Defense in depth.
Includes enabling the test for https://bugzilla.suse.com/show_bug.cgi?id=1177145 which got fixed together with https://bugzilla.suse.com/show_bug.cgi?id=1176402.
=> Test: menu items remain disabled after hotkeys are recomputed

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
Build workers are set up without systemd so the default /run/tmux dir
will not be present (unless clamav pulls systemd in, on SLE)
So we explicitly set the temporary directory to /tmp.
Fixes this build failure: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:D/yast2-ruby-bindings/standard/x86_64
=> Build fix for "error creating /run/tmux/399" (bsc#1178394)

tests/libyui/menu_item_spec.rb
https://trello.com/c/JfDqTpdi/2150-3-menu-bar-refinements
- Start the test example only once for the duration of all 3 sub-tests
- Added a new test case for menu shortcuts priority: After the layout changes, the toplevel menus should still have their preferred keyboard shortcut, and any buttons that compete for the same ones are assigned different ones.
Travis fails to build because the latest versions of libyui and yast-ycp-ui-bindings are not yet available in the Docker image used for building.
- Master PR with the new feature: https://github.com/libyui/libyui/pull/175
- Extended the used UI example: https://github.com/yast/yast-ycp-ui-bindings/pull/61
=> Unit Test for Menu Bar Shortcuts Priority

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
Since libyui does not provide libyui, building with that requires fails.
libyui provides libyui14 etc. (including the SO number), but not the plain symbol libyui.
That means we'd have to adapt the SO number here as well whenever we need to break binary compatibility in our UI packages.
For now, we'll still let the UI test suite fail here if anything changes; that's better than adding another obscure source for build failures.
This supersedes https://github.com/libyui/libyui/pull/176 .
See also the IRC discussion there:
```
[10:59:26] <jreidinger> HuHa: it looks ok, just expect that it will fail when we bump so version due to "Multiple choices" for libyui ( e.g. libyui14 and libyui15 ) and we need to use Prefer in project config
[10:59:44] <HuHa> ok, so it's essentially useless (?) …
```
=> Don't require libyui

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Builtin.cc, src/binary/Yast.cc
- Handle a special keyboard shortcut for starting the installation console ([jsc#PM-1895](https://jira.suse.com/browse/PM-1895), [jsc#SLE-16263](https://jira.suse.com/browse/SLE-16263))
- The implementation is similar to handling the debugging keyboard shortcut
- Related to libyui/libyui#179
- Also fixed build error in Leap 15.2/15.3:
- `Builtin.cc:228:17: error: 'CRYPT_GENSALT_OUTPUT_SIZE' was not declared in this scope`
- Fixed by using the `crypt_gensalt_ra()` function which does not need a static buffer, but it allocates the memory for the result itself (see [`man crypt_gensalt_ra`](https://man.cx/crypt_gensalt(3)))
- Should be also faster as it avoids copying the content of the static buffer
Tested manually with the `repositories` client (uses the `UI::WaitForEvent()` call) and the …
=> Handle installation console keyboard shortcut

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Yast.cc
- Start a graphical menu instead of a low level command line console
- The command line console can be started from there as well
- Related to https://github.com/yast/yast-installation/pull/905
- Related to [jsc#PM-1895](https://jira.suse.com/browse/PM-1895), [jsc#SLE-16263](https://jira.suse.com/browse/SLE-16263)
- Tested manually in installed system
- 4.3.13
=> Change the special keybard shortcut

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/binary/Builtin.cc
The encrypting builtins return `nil` in SLE15-SP2/Leap 15.2 and older, the unit tests fail with
```
Failures:
1) Yast::Builtins.crypt works as expected
Failure/Error: expect(res).to be_a String
expected nil to be a kind of String
```
- See https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-ruby-bindings/SUSE_SLE-15-SP2_GA/aarch64
- Or https://build.opensuse.org/package/live_build_log/YaST:Head/yast2-ruby-bindings/openSUSE_Leap_15.2/x86_64
- It turned out that in the older distros the crypt function returns `EINVAL` error when the passed entropy is `NULL`. In that case we need to explicitly pass some entropy.
- Partially reverts #250
- Related to bsc#1176924
- Tested in Leap 15.1
=> Fixed password encrypting functions in SLE15-SP2/Leap 15.2 and older

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/y2start_helpers.rb
When using **ncurses** with **80x24** the zVM family name is not shown correctly as we can see below.
Found when working in https://bugzilla.suse.com/show_bug.cgi?id=1184474
Use **78** instead of **80** showing the zVM family name completely and also an extra space in **80x24**.
Will fix only in master by now.
=> Adjust the rjust size to show the zVM family name correctly

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/wfm.rb, tests/test_module/clients/wrong_result.rb, tests/wfm_spec.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1187230
Found during manual testing. Not sure about the best solution as result is still exception and internal error ( and it is really our internal fault, but maybe we can present it nicer? )
=> avoid crash caused by missing client argument

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/y2start_helpers.rb
When a signal is sent to YaST (e.g., when the parent terminal is killed), YaST tries writing a message to the standard error output. But stderr can be closed at that time, making YaST to raise an exception.
* https://bugzilla.suse.com/show_bug.cgi?id=1154854
Avoid IO error by doing "exception swallowing"  for *Errno::EIO* while writing to stderr.
See also https://github.com/yast/yast-control-center/pull/51.
Manually tested.
=> Avoid IO exception

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/rspec.rb, src/ruby/yast/rspec/helpers.rb, tests/rspec_helpers_spec.rb
- See https://github.com/yast/yast-packager/pull/599#pullrequestreview-853381879
- Let's share the helper method
- It can also replace the existing stubs like
```ruby
def stub_module(name)
Yast.const_set(name.to_sym, Class.new { def self.fake_method; end })
end
stub_module("Proxy")
```
with 
```ruby
Yast::RSpec::Helpers.define_yast_module("Proxy")
```
=> Added yast/rspec/helpers.rb (related to bsc#1194784)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/y2start_helpers.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1195220
- Enable CN (Common Name) matching in SSL certificates in Go programs (e.g. `suseconnect-ng`). Without it the CN would be ignored and only the SAN (Subject Alternative Name) certificate fields would be used.
- But the self-signed certificates usually only contain the CN field without SAN so YaST could not connect to SMT/RMT
registration servers.
- This error prevented from importing the SSL certificate (that's enabled only for specific known errors): ![cert_cn_problem](https://user-images.githubusercontent.com/907998/152821265-6ec7b800-0c5f-4021-ad84-98cf7e3925ec.png)
- Tested manually, the certificate can be now imported: ![cert_cn_fixed](https://user-images.githubusercontent.com/907998/152821365-d175f272-16ce-4ad2-a3d7-754e280c1bc1.png) …
=> Set "x509ignoreCN=0" GODEBUG environment variable (bsc#1195220)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/y2start_helpers.rb, src/y2start/y2start, tests/y2start_helpers_spec.rb
When running YaST in a container we need to somehow detect that YaST should manage the system mounted in the /mnt and not the container itself.
- Lets use `YAST_SCR_TARGET` environment variable for that
- Initialize SCR in the target chroot when starting YaST
- See related https://github.com/yast/yast-yast2/pull/1258
=> Support managing system in a chroot (bsc#1199840)

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec
Build failure in IBS
- https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-ruby-bindings/SUSE_Factory_Head/x86_64
- https://bugzilla.suse.com/show_bug.cgi?id=1209098
Fix dependency versioning
Tested building in OBS (3.2) and IBS (3.1)
N/A
=> Default ruby is older

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, profiling/yast_import.rb, src/binary/YRubyNamespace.cc, src/ruby/yast/exportable.rb, src/ruby/yast/path.rb, src/ruby/yast/yast.rb, tests/exportable_spec.rb, tests/test_module/modules/InvalidTypeModule.rb
Agame and also yast consume quite bit of memory, so lets try to optimize it.
Add some profiling code and based on it, apply some optimization.
Optimization results ( testing on Leap15.4 so with ruby 2.5 ) just totals:
Original result:
```
Total allocated: 33846260 bytes (365250 objects)
Total retained:  5387014 bytes (47980 objects)
```
after first optimization:
```
Total allocated: 32843452 bytes (364422 objects)
Total retained:  5383110 bytes (47979 objects)
```
after second optimization:
```
Total allocated: 31132062 bytes (351286 objects)
Total retained:  4337427 bytes (41452 objects)
```
So result is roughly saved **2650 KiB** of allocated and in persistent it is **1021 KiB** on testing  sample that just require yast and imports some yast modules.
=> Optimize memory used by the `publish` calls

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, profiling/yast_import.rb, src/binary/YRubyNamespace.cc, src/ruby/yast/exportable.rb, src/ruby/yast/path.rb, src/ruby/yast/yast.rb, tests/exportable_spec.rb, tests/test_module/modules/InvalidTypeModule.rb
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
Backport both fixes (#288 and #289) , so it is same as 4.6.2.
=> Backport sp6

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/ruby/yast/logger.rb, src/ruby/yast/yast.rb
In ruby 3.4 backtrace format changed and yast2-ruby-bindings rely on it.
Fix the code to work with both older and newer ruby.
- already covered by existing tests. I run with new ruby in staging:L
=> Adapt code to ruby 3.4

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, tests/CMakeLists.txt, tests/integration/std_streams_spec.rb
The integration test in yast2-ruby-bindings that test integration with libyui is quite fragile and often fails on non-intel architectures.
disable tests for master as plan is to move away from libyui, so the drawbacks outweighs benefits.
=> disable libyui integration tests in ruby-bindings as it is not reliable

package/yast2-ruby-bindings.spec
Use `%make_build`
instead of SUSE-specific `%jobs` macro,
because %jobs caused issues with reproducible builds (bsc#1237231).
=> Use %make_build

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/y2start/y2start
https://bugzilla.suse.com/show_bug.cgi?id=1243018
YaST is only used as a library for the Agama backend in SLES-16 / Leap 16.
The functionality of YaST goes much further, but  we cannot guarantee that all the details and all the behavior in YaST are compatible in every detail with SLES-16 / Leap 16. This will create pitfalls for users who may find a way to still use YaST functionality that will then increasingly be outdated.
In long run, this will be true for Factory / Tumbleweed as well.
So we are starting to prevent pitfalls with this: The YaST command line  interface (CLI) should not be accessible anymore. This is even more important because this is an aspect of YaST that is less commonly used and thus less thoroughly tested.
This PR makes the YaST  CLI unaccessible: When trying to use …
=> Drop YaST Command Line Interface Support

package/yast2-ruby-bindings.changes, package/yast2-ruby-bindings.spec, src/y2start/y2start
The last PR #295 caused build problems in OBS for other YaST packages, so the SR for OBS Factory was rejected. This means that we now have different versions in YaST:Head and in openSUSE:Factory which is obviously bad.
Some unit tests in other packages are checking the CLI, and with the CLI generally disabled those unit tests now failed which makes the whole build of that package fail.
Revert that last PR.
- Go through all YaST packages one by one and check which ones have unit tests for the CLI and disable or remove those unit tests.
- Set up a build project with this patch and all other YaST packages and wait which ones fail and then disable or remove those unit tests.
Both approaches cause a lot of additional work; it is questionable if that is justified with regard to the expected …
=> Revert #295: Drop YaST CLI
